### ISSUE TITLE
Admin console: Organisation

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/clinicplus#10]
1. The address is not displayed in the user list.
* click admin organizations view, click user list.
2. The organization, all user edit save is not working.
* click admin organizations view, click user list, edit user and save.
3. The organization, all user filter created and updated date is not working for equality [=].
* click admin organizations view, click user list, filter users using =.
4. If we click all user Cancel Button it closes all the pages and displays landing page.
* click admin organizations view, click user list, click all user page cancel button.
5. admin console, create and edit organization is saved without entering mandatory fields.
* click admin organization, click add organization, enter the only name, state, country and contact person name and save.
6. admin organizations, organization type displayed [object object].
7. admin organizations page columns config apply is not working properly.
* click admin organizations, select columns config and apply, click organization view and come back or refresh the page, applied columns are not present.
* above 7th issue present in organization user list.
9. admin organizations, organization billing, user limit is present two times.
10. admin organizations, organization setting, print header, and footer image are not displayed properly.
11. admin organizations, organization setting, the mandatory field is not working properly.
12. remove selected count in the table footer in organizations.
13. The organization print header and footer are not displayed in print.
14. Enabled Features is not working.

15. above issues present in sales console also

**Comment by srikanth340** [comment]
1. The address is not displayed in the user list.
* click admin organizations view, click user list.     [Not issue]

2. The organization, all user edit save is not working.
* click admin organizations view, click user list, edit user and save. [Fixed]

3. The organization, all user filter created and updated date is not working for equality [=].
* click admin organizations view, click user list, filter users using =.  [Not issue] Ask Sir

4. If we click all user Cancel Button it closes all the pages and displays landing page.
* click admin organizations view, click user list, click all user page cancel button. [Fixed]

5. admin console, create and edit organization is saved without entering mandatory fields.
* click admin organization, click add organization, enter the only name, state, country and contact person name and save.  [Fixed]

6. admin organizations, organization type displayed [object object].  [Not observed]
7. admin organizations page columns config apply is not working properly.   [Fixed]
* click admin organizations, select columns config and apply, click organization view and come back or refresh the page, applied columns are not present.
* above 7th issue present in organization user list.
9. admin organizations, organization billing, user limit is present two times. [Fixed]
10. admin organizations, organization setting, print header, and footer image are not displayed properly. [Fixed]
11. admin organizations, organization setting, the mandatory field is not working properly.
12. remove selected count in the table footer in organizations. [Not issue]
13. The organization print header and footer are not displayed in print. [Not observed]
15. above issues present in sales console also

**Comment by urmadhan** [comment]
6. admin organizations, organization type displayed [object object].  [Not Fixed]
