### ISSUE TITLE
Admin console: Products

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/clinicplus#17]
1. The product number is not displayed.
* create a product.
2. Unable to display view product dialog,
* click on view product, edit product dialog is displayed.
3. admin products page columns config apply is not working properly.
* click admin products, select columns config and apply, refresh the page, applied columns are not present.
4. product Purchase Price column string is wrong [ Purchage Price ] is present.
5. In place order, add product to cart, unable to change the discount.
* give the permission to change discount and check in organization place order.
6. In place order, pay is not working, after the amount paid still pay amount is present.
7. after deleting the product, in place order cart and add to cart is not working properly.
8. The product filter date is not working for equality [=].
9. above issues present in sales console also.

**Comment by srikanth340** [comment]
1. The product number is not displayed.
* create a product.

2. Unable to display view product dialog, [View not required]
3. admin products page columns config apply is not working properly. [Frame work issue] sir will fix it
4. product Purchase Price column string is wrong [ Purchage Price ] is present.
5. In place order, add product to cart, unable to change the discount.
6. In place order, pay is not working, after the amount paid still pay amount is present. [Not observed]
7. after deleting the product, in place order cart and add to cart is not working properly.
8. The product filter date is not working for equality [=].   [won't work with = ]
9. above issues present in sales console also.

**Comment by urmadhan** [comment]
Fixed
