### ISSUE TITLE
Filter for order is not working for [ =, !=, >, <= ] operation

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/clinicplus#30]
**STEPS**
1)Click on  options
2)Click on pathology order
3)Click on filter
4)Check for operation like =,!=,>,<=

**OBSERVATION**
Filter for order is not working for above operation

**Comment by crawlinknetworks** [comment]
Operators in the filter are optimized based on the field type.

**Comment by crawlinknetworks** [comment]
Fixed.
