### ISSUE TITLE
Unable to create test item

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/clinicplus#31]
**STEPS**
1)Click on settings
2)Click on pathology test item
3)Click on add new test
4)Enter only for mandatory fields or enter full details

**OBSERVATION**
Unable to create test item

**Comment by crawlinknetworks** [comment]
It is a serverside issue, the upload data body refactors not working properly.

**Comment by crawlinknetworks** [comment]
Fixed. Working now
