### ISSUE TITLE
Unable to edit test item [Validation Error]

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/clinicplus#36]
**STEPS**
1)Click on settings
2)Click on pathological test item
3)Click on edit option
4)Make some changes
5)Click on save 

**OBSERVATION**
Error message is displayed
![testedit3](https://user-images.githubusercontent.com/54259562/71504236-a36d1400-289e-11ea-94a8-4723313d2740.png)

**Comment by srikanth340** [comment]
Issue fixed
