### ISSUE TITLE
Patient Issue

### ISSUE THREAD

**Issue by balajin958** [crawlinknetworks/clinicplus#37]
1)Date of birth is accepting further date while creating patients
2)Description is not saved after creating patience

**Comment by crawlinknetworks** [comment]
Date validation added in   patient create control ;
```ts
 { id: 2, sel: 1, type: 'date', key: 'dob', label: 'Date Of Birth', colClass: 'col-md-3', transform: 'date', validate: 'required|date:1900/01/01:' + Date.now(), required: true },
```

**Comment by balajin958** [comment]
Description is not saved after creating patience this issue is not fixed
