### ISSUE TITLE
Create user profile

### ISSUE THREAD

**Issue by crawlinknetworks** [crawlinknetworks/clinicplus#5]
Create user profile screen in Clinic Plus application

It should content complete user information including name phone number email etc

Also it should contain the last login information like when he logged in through to mobile or web application
It should contain information about the mobile device he is being used and mobile application version and OS version

The profile screen must content a option to change the password

**Comment by srikanth340** [comment]
Profile component is created with password change.
But it need the device details and login info to display.
password type is not there in view controller in framework.
